# Generated by Django 6.0.2 on 2026-02-13 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vendor_active_deal_vendor_deal_description_and_more'),
        ('streetdeal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streetdeal',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='streetdeal',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='streetdeal',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
