# Generated by Django 6.0.2 on 2026-02-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('food', 'Food / Chaat'), ('fruit', 'Fruit Seller'), ('flower', 'Flower Seller'), ('tea', 'Tea Stall'), ('misc', 'Miscellaneous')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('is_female_owned', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('hygiene_rating', models.FloatField(default=3.0)),
                ('service_rating', models.FloatField(default=3.0)),
                ('hygiene_rating_count', models.IntegerField(default=0)),
                ('service_rating_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
