# Generated by Django 6.0.2 on 2026-02-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_streetdeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreetDeal',
        ),
    ]
